### ISSUE TITLE
TBody equation

### ISSUE THREAD

**Issue by jcecconi** [melexis/mlx90632-library#18]
Hi, I'm working with mlx90632 medical version, and I can't find how to calculate TBody (Body Temperature) as melexis software does. Datasheet and libraries only mention how to calculste object temperature, which I can calculate right but it is lower than TBody for near 3°C
Thanks

**Comment by LBuydens** [comment]
That is correct.  
The formula to determine body temperature from forehead temperature is normally IP of our customers.  We do have our own Melexis IP, but this is not freely available.  Please contact your distributor for more information.

**Comment by jcecconi** [comment]
That is not mentioned on any place neither datasheet nor melexis web site...I can't believe it. After buying the Eval Board for mlx90632 We expected to make a fast prototype forehead Thermometer to comply our requirements from Our clients

**Comment by ronaldpace** [comment]
I agree, if you offer a medical grade sensor, you should have a means to have your customers prove this is correct.

**Comment by Letme** [comment]
How is calculation of core body temperature from either forehead, wrist, chest connected to the temperature measured by a temperature sensor? I am sure we can all agree that you can use any temperature sensor to measure the forehead temperature and then covert that to body core tempersture. How does that change with skin color, with activity intensity etc.?

This is why such calculations and collerations are the Intellectual Property of Melexis customers as it is not dependent on sensor measuring the temperature.

**Comment by LBuydens** [comment]
> I agree, if you offer a medical grade sensor, you should have a means to have your customers prove this is correct.

Our customers do have a means to check if our sensor is working properly: In ASTM1965, a laboratory test and a clinical test is defined.  The laboratory test uses calibrated equipment to measure absolute temperatures.  The clinical test uses patients with and without fever to measure their fever.  Our customers use the laboratory test to make sure our senosr is calibrated according the ASTM1965 standard.

**Comment by ronaldpace** [comment]
> > I agree, if you offer a medical grade sensor, you should have a means to have your customers prove this is correct.
> 
> Our customers do have a means to check if our sensor is working properly: In ASTM1965, a laboratory test and a clinical test is defined. The laboratory test uses calibrated equipment to measure absolute temperatures. The clinical test uses patients with and without fever to measure their fever. Our customers use the laboratory test to make sure our senosr is calibrated according the ASTM1965 standard.

Thank you for the information.

**Comment by AjaxCDL** [comment]
Also, it is observed that when the sensor is pointed at the hand or chest of a person, it takes about 17 minutes to get a stable surface temperature.  The surface is off by about 3 degrees F. Does anyone have an observation how to correct this and get the correct surface temperature in a short time (such as 500ms or 1 sec)?

**Comment by Letme** [comment]
Hands are usually much cooler than the core temperature and I am not sure how do you get a reference temperature of the hand. Do you take same emissivity with MLX90632 and other reference sensor?

Chest is strange position to measure temperature - how do you do that? I have hairy chest, so measuring skin temperature there is going to be difficult as hair changes emissivity of the surface (darker) as well as they are cooler, since they "float" in the air. I think this is not related to TBody equation as this moment, so lets discuss that in #48

**Comment by Letme** [comment]
Sales team should be a default point of contact for people that want to have some more information about body core temperature calculations. The current driver will not include that, because what we have is not medically verified, so we do not want to cause any confusion.
I assume my above project outlines some of the difficulties of the body temperature calculations.
