### ISSUE TITLE
Example to set the extended IR mode 

### ISSUE THREAD

**Issue by MahendraSondagar** [melexis/mlx90632-library#23]
Hi... there 
I'm using the default example with STM32, from where I'm getting object and ambient temperature 
The temperature almost seems constant, but when I touch to sensor then and only then it's increasing 
I'm expecting Non-contact type IR 
I've gone through the datasheet 
It seems I need to set for the extended mode 

I got the .c file for the Extended mode, but I'm also expecting the example code of it 
That would be great if you can help 
Thanks

**Comment by Letme** [comment]
I think this is more then fitting into `mlx90632-example` repo?

Anyway, are you sure your sensor is supporting the extended mode? Even without extended mode the values should change with old formula and without contact unless something is obscuring the sensor field of view (this is first thing I would check). Does your setup have a lens over the sensor?

Probably @slavysis can put the general (non stm specific) example flow in README, below current example description of the normal flow.

**Comment by MahendraSondagar** [comment]
Hi guys...
Thanks for the reply 
The problem is, I'm not getting the Non-contactless functionality 
Even I've been trying with the default STM 32 code and Arduino 
But the result is the same!
It's working when I touch the sensor 
I have custom made a breakout  board which I have shared here for your reference 
**right now, I don't have any cone shape plastic cap or glass on top of it for the FOV**
**is it necessary?**
**My application is for the Medical grade IR thermal sensing which is quite similar to the demo that you guys showed at your YouTube channel
[TEMP Sensor- MLX90632.pdf](https://github.com/melexis/mlx90632-library/files/5177627/TEMP.Sensor-.MLX90632.pdf)
** 
[https://www.youtube.com/watch?v=SNvl5HdzIL4](url)

**Comment by LBuydens** [comment]
Hi, this forum is more intented for software support.  From what I see I suppose that is not the problem.  

The MLX90632 gives 2 temperatures, the To object temperature and Ta, ambient temperature.  Are you looking at the right temperature?  
If indeed To does not vary or = Ta always, could you make a log of the raw data readings and calculated temperatures?  With that data please contact your distributor for support, or alternatively, contact sales@melexis.com.

**Comment by cakira** [comment]
Hi! I'm not affiliated with Melexis and I came here just searching for example code to work with the extended range.
However, maybe I can help @MahendraSondagar .

As @LBuydens said, the Melexis sensor reads 2 temperatures, the ambient and the object temperature. By your description, it does seem you are reading only the ambient temperature (the sensor's temperature) and you are interested in the object temperature.

Regarding the IR light question, the sensor doesn't need to emit IR light, because every matter in the universe already emits infrared light by itself and the Melexis sensor just measures it. Depending on the precision of the measurement, it's important to learn the concepts because the calculus of the temperature depends on the body [emissivity](https://en.wikipedia.org/wiki/Emissivity), which depends on the body you are measuring. Melexis used 1.0 as default emissivity, but this is true only for a perfect [black body](https://en.wikipedia.org/wiki/Black_body).

**Comment by 4BH1J337** [comment]
Hi
First of all, MLX90632 is not an Active IR sensor So, it could not emit any kind of IR radiation maybe you need to read the datasheet before playing with the sensor. 
 https://www.melexis.com/en/search#q=mlx90632
Your Problem related to two things maybe you only enable ambient temperature reading 
or there is some kind of physical problem may be the sensor or opponents damage

**Comment by Letme** [comment]
I am closing this issue as resolved since there has been couple of years since last reply and author hopefully solved it as well. It does not seem to be a software issue at least at first glance.
